add missing #include <cstdint>
In file included from s/testencoder.cpp:15:
s/basexy/encoder.hpp:40:13: error: 'uint8_t' has not been declared
   40 |   auto push(uint8_t c)
      |             ^~~~~~~